create table IF NOT EXISTS purchase_dynamic_qr
(
    id            bigint generated by default as identity
        primary key,
    code          varchar(255) not null,
    brand         varchar(255) not null,
    commerce_type varchar(255) not null
);

create table IF NOT EXISTS purchase_qr
(
    id                  bigint generated by default as identity
        primary key,
    enabled             boolean      not null,
    commerce_type       varchar(255) not null,
    brand               varchar(255) not null,
    qr                  text         not null,
    dynamic_simple_code varchar(255) not null,
    simple_code         varchar(255) not null,
    transaction_id      uuid         not null,
    token_uuid          uuid         not null,
    dynamic_token_uuid  uuid         not null,
    timestamp           timestamp(6) not null
);
